version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
       ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59    
    shm_size: '1gb'   
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: 5311072/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=search-module.xml
    volumes:
      - ./search-result:/usr/share/automation/output      
  book-flight-module:
    image: 5311072/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=book-flight-module.xml
    volumes:
      - ./book-result:/usr/share/automation/output   